name: Generic pipeline integration
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.quay_username }}
          password: ${{ secrets.quay_pass }}

      - name: Run the build script
        run: make build
      - name: Run the test script
        run: make test
      # - name: Run the deploy script
      #   working-directory: ${{ inputs.path }}
      #   run: make deploy
